#include <math.h>
#include <cmsis_dsp/Include/arm_math.h>
#include <tinyara/clock.h>

#define SEMIHOSTING

#if defined(SEMIHOSTING)
#include <stdio.h>
#endif

/* ----------------------------------------------------------------------
* Defines each of the tests performed
* ------------------------------------------------------------------- */
#define MAX_BLOCKSIZE   1000
#define DELTA           (0.0001f)

/* ----------------------------------------------------------------------
* Test input data for Floating point sin_cos example for 32-blockSize
* Generated by the MATLAB randn() function
* ------------------------------------------------------------------- */

// const float32_t testInput_f32_arm_cmsis_dsp_libc_math_speed[MAX_BLOCKSIZE] =
// {
//   -1.244916875853235400,  -4.793533929171324800,   0.360705030233248850,   0.827929644170887320,  -3.299532218312426900,   3.427441903227623800,   3.422401784294607700,  -0.108308165334010680,
//    0.941943896490312180,   0.502609575000365850,  -0.537345278736373500,   2.088817392965764500,  -1.693168684143455700,   6.283185307179590700,  -0.392545884746175080,   0.327893095115825040,
//    3.070147440456292300,   0.170611405884662230,  -0.275275082396073010,  -2.395492805446796300,   0.847311163536506600,  -3.845517018083148800,   2.055818378415868300,   4.672594161978930800,
//   -1.990923030266425800,   2.469305197656249500,   3.609002606064021000,  -4.586736582331667500,  -4.147080139136136300,   1.643756718868359500,  -1.150866392366494800,   1.985805026477433800
// };

// extern double testInput[MAX_BLOCKSIZE];
extern double testInput_f64_arm_cmsis_dsp_libc_math_speed[MAX_BLOCKSIZE];
// extern float testInput_f32_arm_cmsis_dsp_libc_math_speed[MAX_BLOCKSIZE];
// extern int testInput_q31_arm_cmsis_dsp_libc_math_speed[MAX_BLOCKSIZE];

/* ----------------------------------------------------------------------
* Declare Global variables
* ------------------------------------------------------------------- */
static uint32_t blockSize = MAX_BLOCKSIZE;


/* ----------------------------------------------------------------------
* CMSIS-DSP, libc/math speed test
* ------------------------------------------------------------------- */

arm_status status_arm_cmsis_dsp_libc_math_speed;

int get_diff_in_ms(struct timespec start, struct timespec end) {
  int sec_diff = end.tv_sec - (int)start.tv_sec;
  int nsec_diff = end.tv_nsec - (int)start.tv_nsec;
  return sec_diff * 1000 + nsec_diff / 1000000;
}

float arm_vlog_f32_wrapper(float input) {
  float output;
  arm_vlog_f32(&input, &output, 1);
  return output;
}

float arm_abs_f32_wrapper(float input) {
  float output;
  arm_abs_f32(&input, &output, 1);
  return output;
}

int arm_abs_q31_wrapper(int input) {
  int output;
  arm_abs_q31(&input, &output, 1);
  return output;
}

double normalized_sin(double input) {
  input = fmod(input, 2.0 * M_PI);
  if (input > M_PI) {
		input -= 2.0 * M_PI;
	} else if (input < -M_PI) {
		input += 2.0 * M_PI;
	}
	return (double)arm_sin_f32((float)input);
}

int is_double_convertable_to_float(double d) {
  if (isnan(d) || isinf(d)) {
    return 1;
  }

  if(d > FLT_MAX || d < -FLT_MAX) {
    return 0;
  }

  float f = (float)d;
  return d == (double)f;
}

double branch_sin(double input) {
  if(is_double_convertable_to_float(input)) {
    return (double)arm_sin_f32((float)input);
  }
  return sin(input);
}

int32_t arm_cmsis_dsp_libc_math_speed_test_example(void)
{
  uint32_t i;
  uint32_t j;
  double output1[10];
  double output2[10];
  struct timespec startTime;
  struct timespec endTime;
  float diff;
  
  printf("============== log 함수 원형 ==============\n");
  clock_gettime(CLOCK_REALTIME, &startTime);
  printf("s\n");
  for(j = 0; j < 1000000; j++) {
    for(i = 0; i < 10; i++) {
      output2[i] = log(testInput_f64_arm_cmsis_dsp_libc_math_speed[i]);
    }
  }
  printf("e\n");
  clock_gettime(CLOCK_REALTIME, &endTime);
  printf("libc/math log: %d ms\n", get_diff_in_ms(startTime, endTime));
  printf("libc/math start time: %d sec, %d nsec\n", startTime.tv_sec, startTime.tv_nsec);
  printf("libc/math end time: %d sec, %d nsec\n", endTime.tv_sec, endTime.tv_nsec);

  printf("============== comapre arm_vlog_f32, log ==============\n");
  printf("============== 강제 형 변환 ==============\n");
  
  clock_gettime(CLOCK_REALTIME, &startTime);
  printf("s\n");
  for(j = 0; j < 1000000; j++) {
    // for(i = 0; i < 10; i++) {
      arm_vlog_f32(testInput_f64_arm_cmsis_dsp_libc_math_speed, output1, 10);
    // }
  }
  printf("e\n");
  clock_gettime(CLOCK_REALTIME, &endTime);
  printf("CMSIS-DSP arm_vlog_f32: %d ms\n", get_diff_in_ms(startTime, endTime));
  printf("CMSIS-DSP start time: %d sec, %d nsec\n", startTime.tv_sec, startTime.tv_nsec);
  printf("CMSIS-DSP end time: %d sec, %d nsec\n", endTime.tv_sec, endTime.tv_nsec);

  for(i = 0; i < 10; i++) {
    diff = fabs(output1[i] - output2[i]);
    // if(diff) {
      printf("CMSIS-DSP and libc/math log results differ at input: %.16lf, arm_vlog_f32: %.16lf, logf: %.16lf, diff: %.16lf\n", i, testInput_f32_arm_cmsis_dsp_libc_math_speed[i], output1[i], output2[i], diff);
    // }
  }

  // printf("============== sin 함수 원형 ==============\n");
  // clock_gettime(CLOCK_REALTIME, &startTime);
  // printf("s\n");
  // for(j = 0; j < 10000000; j++) {
  //   for(i = 0; i < 10; i++) {
  //     output2[i] = sin(testInput[i]);
  //   }
  // }
  // printf("e\n");
  // clock_gettime(CLOCK_REALTIME, &endTime);
  // printf("libc/math sin: %d ms\n", get_diff_in_ms(startTime, endTime));
  // printf("libc/math start time: %d sec, %d nsec\n", startTime.tv_sec, startTime.tv_nsec);
  // printf("libc/math end time: %d sec, %d nsec\n", endTime.tv_sec, endTime.tv_nsec);

  // printf("============== comapre arm_sin_f32, sin ==============\n");
  // printf("============== 강제 형 변환 ==============\n");
  
  // clock_gettime(CLOCK_REALTIME, &startTime);
  // printf("s\n");
  // for(j = 0; j < 10000000; j++) {
  //   for(i = 0; i < 10; i++) {
  //     output1[i] = (double)arm_sin_f32((float)testInput[i]);
  //   }
  // }
  // printf("e\n");
  // clock_gettime(CLOCK_REALTIME, &endTime);
  // printf("CMSIS-DSP arm_sin_f32: %d ms\n", get_diff_in_ms(startTime, endTime));
  // printf("CMSIS-DSP start time: %d sec, %d nsec\n", startTime.tv_sec, startTime.tv_nsec);
  // printf("CMSIS-DSP end time: %d sec, %d nsec\n", endTime.tv_sec, endTime.tv_nsec);

  // for(i = 0; i < 10; i++) {
  //   diff = fabs(output1[i] - output2[i]);
  //   // if(diff) {
  //     printf("CMSIS-DSP and libc/math sin results differ at input: %.16lf, arm_sin_f32: %.16lf, sin: %.16lf, diff: %.16lf\n", i, testInput[i], output1[i], output2[i], diff);
  //   // }
  // }

  // printf("============== comapre arm_sin_f32, sinf ==============\n");
  // printf("============== 정규화 ==============\n");
  
  // clock_gettime(CLOCK_REALTIME, &startTime);
  // printf("s\n");
  // for(j = 0; j < 10000000; j++) {
  //   for(i = 0; i < 10; i++) {
  //     output1[i] = normalized_sin(testInput[i]);
  //   }
  // }
  // printf("e\n");
  // clock_gettime(CLOCK_REALTIME, &endTime);
  // printf("CMSIS-DSP arm_sin_f32: %d ms\n", get_diff_in_ms(startTime, endTime));
  // printf("CMSIS-DSP start time: %d sec, %d nsec\n", startTime.tv_sec, startTime.tv_nsec);
  // printf("CMSIS-DSP end time: %d sec, %d nsec\n", endTime.tv_sec, endTime.tv_nsec);

  // for(i = 0; i < 10; i++) {
  //   diff = fabs(output1[i] - output2[i]);
  //   // if(diff) {
  //     printf("CMSIS-DSP and libc/math sin results differ at input: %.16lf, arm_sin_f32: %.16lf, sin: %.16lf, diff: %.16lf\n", i, testInput[i], output1[i], output2[i], diff);
  //   // }
  // }

  // printf("============== comapre arm_sin_f32, sinf ==============\n");
  // printf("============== 타입 분기 ==============\n");
  
  // clock_gettime(CLOCK_REALTIME, &startTime);
  // printf("s\n");
  // for(j = 0; j < 10000000; j++) {
  //   for(i = 0; i < 10; i++) {
  //     output1[i] = branch_sin(testInput[i]);
  //   }
  // }
  // printf("e\n");
  // clock_gettime(CLOCK_REALTIME, &endTime);
  // printf("CMSIS-DSP arm_sin_f32: %d ms\n", get_diff_in_ms(startTime, endTime));
  // printf("CMSIS-DSP start time: %d sec, %d nsec\n", startTime.tv_sec, startTime.tv_nsec);
  // printf("CMSIS-DSP end time: %d sec, %d nsec\n", endTime.tv_sec, endTime.tv_nsec);

  // for(i = 0; i < 10; i++) {
  //   diff = fabs(output1[i] - output2[i]);
  //   // if(diff) {
  //     printf("CMSIS-DSP and libc/math sin results differ at input: %.16lf, arm_sin_f32: %.16lf, sin: %.16lf, diff: %.16lf\n", i, testInput[i], output1[i], output2[i], diff);
  //   // }
  // }
  
  // printf("============== comapre arm_cos_f32, cosf ==============\n");

  // clock_gettime(CLOCK_REALTIME, &startTime);
  // printf("s\n");
  // for(j = 0; j < 100000; j++) {
  //   for(i = 0; i < blockSize; i++) {
  //     output1[i] = arm_cos_f32(testInput_f32_arm_cmsis_dsp_libc_math_speed[i]);
  //   }
  // }
  // printf("e\n");
  // clock_gettime(CLOCK_REALTIME, &endTime);
  // printf("CMSIS-DSP arm_cos_f32: %d ms\n", get_diff_in_ms(startTime, endTime));
  // printf("CMSIS-DSP start time: %d sec, %d nsec\n", startTime.tv_sec, startTime.tv_nsec);
  // printf("CMSIS-DSP end time: %d sec, %d nsec\n", endTime.tv_sec, endTime.tv_nsec);

  // clock_gettime(CLOCK_REALTIME, &startTime);
  // printf("s\n");
  // for(j = 0; j < 100000; j++) {
  //   for(i = 0; i < blockSize; i++) {
  //     output2[i] = cosf(testInput_f32_arm_cmsis_dsp_libc_math_speed[i]);
  //   }
  // }
  // printf("e\n");
  // clock_gettime(CLOCK_REALTIME, &endTime);
  // printf("libc/math cosf: %d ms\n", get_diff_in_ms(startTime, endTime));
  // printf("libc/math start time: %d sec, %d nsec\n", startTime.tv_sec, startTime.tv_nsec);
  // printf("libc/math end time: %d sec, %d nsec\n", endTime.tv_sec, endTime.tv_nsec);

  // for(i = 0; i < blockSize; i++) {
  //   diff = fabsf(output1[i] - output2[i]);
  //   if(diff) {
  //     printf("CMSIS-DSP and libc/math cos results differ at input: %f, arm_cos_f32: %f, cosf: %f, diff: %f\n", i, testInput_f32_arm_cmsis_dsp_libc_math_speed[i], output1[i], output2[i], diff);
  //   }
  // }
  

  // printf("============== comapre arm_vlog_f32, logf ==============\n");

  // clock_gettime(CLOCK_REALTIME, &startTime);
  // printf("s\n");
  // for(j = 0; j < 10000; j++) {
  //   for(i = 0; i < blockSize; i++) {
  //     output1[i] = arm_vlog_f32_wrapper(testInput_f32_arm_cmsis_dsp_libc_math_speed[i]);
  //   }
  // }
  // printf("e\n");
  // clock_gettime(CLOCK_REALTIME, &endTime);
  // printf("CMSIS-DSP arm_vlog_f32: %d ms\n", get_diff_in_ms(startTime, endTime));
  // printf("CMSIS-DSP start time: %d sec, %d nsec\n", startTime.tv_sec, startTime.tv_nsec);
  // printf("CMSIS-DSP end time: %d sec, %d nsec\n", endTime.tv_sec, endTime.tv_nsec);

  // clock_gettime(CLOCK_REALTIME, &startTime);
  // printf("s\n");
  // for(j = 0; j < 10000; j++) {
  //   for(i = 0; i < blockSize; i++) {
  //     output2[i] = logf(testInput_f32_arm_cmsis_dsp_libc_math_speed[i]);
  //   }
  // }
  // printf("e\n");
  // clock_gettime(CLOCK_REALTIME, &endTime);
  // printf("libc/math logf: %d ms\n", get_diff_in_ms(startTime, endTime));
  // printf("libc/math start time: %d sec, %d nsec\n", startTime.tv_sec, startTime.tv_nsec);
  // printf("libc/math end time: %d sec, %d nsec\n", endTime.tv_sec, endTime.tv_nsec);

  // for(i = 0; i < blockSize; i++) {
  //   diff = fabsf(output1[i] - output2[i]);
  //   if(diff && !isnan(output1[i]) && !isnan(output2[i])) {
  //     printf("CMSIS-DSP and libc/math log results differ at input: %f, arm_vlog_f32: %f, logf: %f, diff: %f\n", i, testInput_f32_arm_cmsis_dsp_libc_math_speed[i], output1[i], output2[i], diff);
  //   }
  // }

  // printf("============== comapre arm_abs_f32, fabs ==============\n");

  // clock_gettime(CLOCK_REALTIME, &startTime);
  // printf("s\n");
  // for(j = 0; j < 100000; j++) {
  //   for(i = 0; i < blockSize; i++) {
  //     output1[i] = arm_abs_f32_wrapper(testInput_f32_arm_cmsis_dsp_libc_math_speed[i]);
  //   }
  // }
  // printf("e\n");
  // clock_gettime(CLOCK_REALTIME, &endTime);
  // printf("CMSIS-DSP arm_abs_f32: %d ms\n", get_diff_in_ms(startTime, endTime));
  // printf("CMSIS-DSP start time: %d sec, %d nsec\n", startTime.tv_sec, startTime.tv_nsec);
  // printf("CMSIS-DSP end time: %d sec, %d nsec\n", endTime.tv_sec, endTime.tv_nsec);

  // clock_gettime(CLOCK_REALTIME, &startTime);
  // printf("s\n");
  // for(j = 0; j < 100000; j++) {
  //   for(i = 0; i < blockSize; i++) {
  //     output2[i] = fabs(testInput_f32_arm_cmsis_dsp_libc_math_speed[i]);
  //   }
  // }
  // printf("e\n");
  // clock_gettime(CLOCK_REALTIME, &endTime);
  // printf("libc/math fabs: %d ms\n", get_diff_in_ms(startTime, endTime));
  // printf("libc/math start time: %d sec, %d nsec\n", startTime.tv_sec, startTime.tv_nsec);
  // printf("libc/math end time: %d sec, %d nsec\n", endTime.tv_sec, endTime.tv_nsec);

  // for(i = 0; i < blockSize; i++) {
  //   diff = fabsf(output1[i] - output2[i]);
  //   if(diff) {
  //     printf("CMSIS-DSP and libc/math fabs results differ at input: %f, arm_abs_f32: %f, absf: %f, diff: %f\n", i, testInput_f32_arm_cmsis_dsp_libc_math_speed[i], output1[i], output2[i], diff);
  //   }
  // }

  // printf("============== comapre arm_abs_q31, abs ==============\n");

  // clock_gettime(CLOCK_REALTIME, &startTime);
  // printf("s\n");
  // for(j = 0; j < 100000; j++) {
  //   for(i = 0; i < blockSize; i++) {
  //     arm_abs_q31_wrapper(testInput_q31_arm_cmsis_dsp_libc_math_speed[i]);
  //   }
  // }
  // printf("e\n");
  // clock_gettime(CLOCK_REALTIME, &endTime);
  // printf("CMSIS-DSP arm_abs_q31: %d ms\n", get_diff_in_ms(startTime, endTime));
  // printf("CMSIS-DSP start time: %d sec, %d nsec\n", startTime.tv_sec, startTime.tv_nsec);
  // printf("CMSIS-DSP end time: %d sec, %d nsec\n", endTime.tv_sec, endTime.tv_nsec);

  // clock_gettime(CLOCK_REALTIME, &startTime);
  // printf("s\n");
  // for(j = 0; j < 100000; j++) {
  //   for(i = 0; i < blockSize; i++) {
  //     abs(testInput_q31_arm_cmsis_dsp_libc_math_speed[i]);
  //   }
  // }
  // printf("e\n");
  // clock_gettime(CLOCK_REALTIME, &endTime);
  // printf("libc/math abs: %d ms\n", get_diff_in_ms(startTime, endTime));
  // printf("libc/math start time: %d sec, %d nsec\n", startTime.tv_sec, startTime.tv_nsec);
  // printf("libc/math end time: %d sec, %d nsec\n", endTime.tv_sec, endTime.tv_nsec);

  status_arm_cmsis_dsp_libc_math_speed = ARM_MATH_SUCCESS;
}